# Generated by Django 5.0.7 on 2024-07-24 12:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile no')),
                ('partner_category', models.CharField(choices=[('1', 'person'), ('2', 'organization'), ('3', 'group')], max_length=1, verbose_name='Partner')),
                ('organisation', models.IntegerField()),
                ('gst_number', models.CharField(max_length=64, verbose_name='GST Number')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'db_table': 'track_businesspartner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('gst_number', models.CharField(max_length=64)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Expired')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'track_organisation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('po_number', models.CharField(max_length=32, verbose_name='PO Number')),
                ('business_partner', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'registered'), ('2', 'approved'), ('3', 'confirmed'), ('4', 'cancelled'), ('5', 'delivered')], max_length=1, verbose_name='Status')),
                ('delivery_date', models.DateField(verbose_name='Delivery Date')),
                ('total_value', models.IntegerField(verbose_name='Total Value')),
                ('weight', models.IntegerField(blank=True, null=True, verbose_name='Weight')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
            options={
                'db_table': 'track_purchaseorderheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_code', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=64)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('domain', models.CharField(max_length=64, null=True)),
                ('description', models.TextField(null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Active'), ('2', 'Expired')], max_length=1, null=True)),
            ],
            options={
                'db_table': 'track_tenant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OraganisationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.IntegerField()),
                ('profile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('purchase_order', models.IntegerField()),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('material_code', models.CharField(max_length=64, verbose_name='Material Code')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('per_unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Per Unit Price')),
                ('per_unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Per Unit Weight')),
                ('unit_of_measurement', models.CharField(max_length=8)),
                ('sgst', models.IntegerField(verbose_name='SGST')),
                ('cgst', models.IntegerField(verbose_name='CGST')),
                ('igst', models.IntegerField(verbose_name='IGST')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Discount')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='StageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('profile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('vehicle_number', models.CharField(max_length=10, verbose_name='Vehicle Number')),
                ('vehicle_tracking_number', models.UUIDField(default=uuid.uuid4, verbose_name='Vehicle Tracking Number')),
                ('purchase_order', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('completed', models.BooleanField(null=True, verbose_name='Completed')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrackingLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_tracking', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('log_type', models.CharField(blank=True, choices=[('1', 'entry'), ('2', 'exit')], max_length=1, null=True)),
                ('skipped', models.BooleanField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTrackingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('stage_order', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('1', 'SuperAdmin'), ('2', 'Admin'), ('3', 'User')], max_length=1, null=True)),
                ('tenant_organisation', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_no', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TargetVsActual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_organisation', models.IntegerField()),
                ('stage', models.IntegerField()),
                ('gate_entry', models.IntegerField()),
                ('table', models.CharField(max_length=64)),
                ('field', models.CharField(max_length=64)),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('target_value', models.CharField(max_length=64)),
                ('actual_value', models.CharField(max_length=64)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
